# Generated by Django 2.2 on 2020-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='img1',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='img2',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='img3',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='img4',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='img5',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='img6',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
